[[cli]]

= Using the CLI

You can get help on the available commands via:

[source]
----
funktion
----

=== Browsing resources

To list all the resources of different kind via:

[source]
----
funktion get connector
funktion get flow
funktion get fn
funktion get runtime
----

=== Deleting resources

You can delete a Connector or flow via:

[source]
----
funktion delete connector foo
funktion delete flow bar
funktion delete fn whatnot
funktion delete runtime nodejs
----

Or to remove all the functions, flows or connectors use `--all`

[source]
----
funktion delete flow --all
funktion delete connector --all
----

=== Installing Runtimes and Connectors

To install the default function runtimes and connectors into your namespace type the following:

[source]
----
funktion install runtime
funktion install connector --all
----

There's over http://camel.apache.org/components.html[200 connectors] provided out of the box. If you only want to install a number of them you can specify their names as parameters

[source]
----
funktion install amqp kafka timer twitter
----

To just get a feel for what connectors are available without installing them try:

[source]
----
funktion install connector --list
----

or for short:

[source]
----
funktion install conn -l
----

=== Configuring Connectors

Various connectors have different configuration properties. For example the `twitter` connector has a number of properties to configure like the secret and token.

So to configure a connector you can type:

[source]
----
funktion edit connector twitter
----

You will then be prompted to enter new values; you can just hit `[ENTER]` to avoid changing a property.

To see a list of all the properties you can type

[source]
----
funktion edit connector twitter -l
----

Then you can pass in specific properties directly via the non-interactive version of the edit command:

[source]
----
funktion edit connector twitter accessToken=mytoken accessTokenSecret=mysecret consumerKey=myconsumerkey consumerSecret=myconsumerSecert
----



=== Creating flows

To create a new flow for a connector try the following:

[source]
----
funktion create flow timer://bar?period=5000 http://foo/
----

This will generate a new `flow` which will result in a new `Deployment` being created and one or more Pods should spin up.

Note that the first time you try out a new Connector kind it may take a few moments to download the docker image for this connector - particularly the first time you use a connector.

Once a pod has started for the `Deployment` you can then view the logs of a flow via

[source]
----
funktion logs flow timer-bar1
----

=== Using kubectl directly

You can also create a flow using `kubectl` directly if you prefer:

[source]
----
kubectl apply -f https://github.com/funktionio/funktion/blob/master/examples/flow1.yml
----

You can view all the Connectors and flows via:

[source]
----
kubectl get cm
----

Or delete them via

[source]
----
kubectl delete cm nameOfConnectorOrflow
----


=== Running the Operator

You can run the funktion operator from the command line if you prefer:

[source]
----
funktion operate
----

Though ideally you'd install the funktion operator by <<install-platform>>

=== Updating the binary

The funktion binary is self updating so you can upgrade your binary to newer versions if they are available via the following command:

[source]
----
funktion update
----


=== Using shell completion

The funktion binary can generate completion for bash and zsh

To generate completion for bash:

[source]
----
source <(funktion completion bash)
----

and for zsh:
source <(funktion completion zsh)